apiVersion: v1
kind: Service
metadata:
  name: {{ include "mynginx2.fullname" . }}
  labels:
    {{- include "mynginx2.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mynginx2.selectorLabels" . | nindent 4 }}
