# Maven master
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

#pool:
#  vmImage: ubuntu-latest

variables:
  # Container registry service connection established during pipeline creation // 'dvue2-acr-evue2dsoacr-sc'
  dockerRegistryServiceConnection:  'dvue-acr-evuedsoacr-sc'
  azureResourceGroupForACR:  'dvue-acr-rg'
  # e.g.  nginx
  imageRepository: 'ava/guoyang/test/test-tomcat'
  containerRegistry: 'evuedsoacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  k8sServiceConnection: 'k8s_connection_dvueappaks2'
  k8sNamespace: 'pipeline-dev'
  k8sImagePullSecrets: 'pipeline-deploy'
  tag: '$(Build.BuildId)'


steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: HelmInstaller@1
  displayName: Helm 3.7.2 installer
  inputs:
    helmVersionToInstall: 3.7.2

- task: HelmDeploy@0
  displayName: Helm package
  inputs:
    command: package
    #chartPath: Application/charts/mynginx2
    chartPath: ./charts/mynginx2
    destination: $(Build.ArtifactStagingDirectory)

- script: date
  displayName: Get the date
- script: dir
  workingDirectory: $(Agent.BuildDirectory)
  displayName: List contents of a folder
- script: |
    set MYVAR=foo
    set
  displayName: Set a variable and then display all
  env:
    aVarFromYaml: someValue

- task: HelmDeploy@0
  displayName: Helm save
  inputs:
    command: push
#    chartNameForACR: $(containerRegistry)/test/mynginx2:0.1.3
    chartNameForACR: test/mynginx2:0.1.3
    #chartPathForACR: Application/charts/sampleapp
    chartPathForACR: ./charts/mynginx2
#    azureSubscriptionEndpointForACR: $(k8sServiceConnection)
#    azureResourceGroupForACR: $(azureResourceGroupForACR)
    azureContainerRegistry: $(containerRegistry)
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: $(k8sServiceConnection)
    arguments: $(Build.ArtifactStagingDirectory)/mynginx2-0.1.3.tgz oci://$(containerRegistry)/helm/test
  env:
    HELM_EXPERIMENTAL_OCI: 1



