apiVersion : apps/v1
kind: Deployment
metadata:
  name: tomcat-helloworld-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-helloworld
  template:
    metadata:
      labels:
        app: tomcat-helloworld
    spec:
      containers:
        - name: tomcat-helloworld-deploy
          image: evuedsoacr.azurecr.io/ava/guoyang/test/test-tomcat
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
      serviceAccountName: pipeline-deploy