apiVersion: v1
kind: Service
metadata:
  name: svc-lb-internal-tomcat-helloworld
  namespace: pipeline-dev
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: tomcat-helloworld

